### ISSUE TITLE
Send automated emails to users when specific conditions are met

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/advocacy-tracker-client#11]
Use cases for automated emails could be e.g.

- send an email to a user when assigned a new task
- send an email to a user when task is due 
- send an email to a user when tagged in a comment

---
requires #10

**Comment by tmfrnz** [comment]
TODO: define rules

**Comment by tmfrnz** [comment]
### 1. "activity assigned"

an "activity assigned" email notification is sent to the user for each new assignment if

* the user is not assigning themself
* the activity has email-notifications enabled (requires new field in table)
* the activity has a publication status of "published"

email should contain

* link to the task (requires storing the client activity path ion the server settings)

_likewise an email notification is to be send when a user is unassigned from an activity_

---

### 2. "activity assigned on publication status change" 

an "activity assigned" email notification is sent to each assigned user if

* the activity has email-notifications enabled (requires new field in table)
* the activity's publication status is changed from "draft" to "published" 

email should contain

* link to the task (requires storing the client activity path ion the server settings)

---

### 3. "task updated"

a "task updated" email notification is sent to each assigned user (except the user responsible for the change) for each change to a task record (activities with activitytype = 5) or any changes to its relationships (created/removed/changed) if

* the activity has email-notifications enabled (requires new field in table)
* the activity has a publication status of "published" (no "task updated" notification is sent when it previously had a status of "draft" as this is covered by 2)

email should contain

* link to the task (requires storing the client activity path ion the server settings)
* **to clarify: should the email also state what the changes are?** (would be a bit more complicated than just saying that there has been an unspecified update)

_note: as changes to task attributes and relationships are individual transactions (saving a record will first update the record's attributes, then create, delete or modify each of the new, removed or changed relationships) multiple email notifications would be sent out, one for each individual update_

_also note: repeated change of publication status, ie from draft to published, then from published to draft and again from draft to published would trigger a repeated notification)_

---

### 4. "task reminder" 

a "task reminder" email notification is sent to all assigned users if the last update to the task (or any of its relationships) was older than 7 days (or otherwise configured)

**to clarify: how often should this be checked? daily? weekly?**

**Comment by hohuuhuy** [comment]
## General questions

- Does the note in the "task updated" mean that multiple emails would be sent if multiple relationships are updated? For example, if I tag 5 more contacts to a task, would the assigned user(s) receive 5 emails?
- If assigned user(s) receive 2 separate emails, one on the updated attribute of the task, and one on the updated relationships of the task, can we prevent this by setting a rule to check for new transactions on a task every minute and send one email if there is any transaction recorded, rather than sending one email for every transaction?

## General comments

- The rules overall look quite clear and make sense, I think we can start working on these in the test version to see how well they work
- Clarification on some details:
    - "Task updated" emails do not need to specify the change, I think the title of the task, and the link to the task, would be sufficient
    - Frequency of check for "Task reminder": I think daily, but maybe we can discuss more on the implications for this choice and decide together.

**Comment by tmfrnz** [comment]
- will also need to make sure we only consider real updates!

**Comment by tmfrnz** [comment]
@hohuuhuy I have since created the following tasks on the server-side repository:

- Measure assigned: https://github.com/dumparkltd/advocacy-tracker-server/issues/50
- Task reminder: https://github.com/dumparkltd/advocacy-tracker-server/issues/48
- Task updated: https://github.com/dumparkltd/advocacy-tracker-server/issues/49

Related are:

- new field `notifications`: https://github.com/dumparkltd/advocacy-tracker-server/issues/47
- new field `relationship_updated_at`: https://github.com/dumparkltd/advocacy-tracker-server/issues/46


These should pretty much capture what we need but there are also still some small aspects that are yet to be determined. Of course we do not have to *and will likely not) get it 100% from the start as we can also always update and tweak those rules later. So yeah please have a look and let me know if you have any questions or remarks.

**Comment by tmfrnz** [comment]
- [ ]  also update password reset emails
