### ISSUE TITLE
Optimise print / export PDF

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/advocacy-tracker-client#138]

**Comment by vbojilova** [comment]
print optimization edits: 

- [ ] show active filters in list views

- [ ] remove irrelevant query args in URL (e.g. "view" from single pages)

- [ ] page view: lists styles (e.g. about)

- [ ] page view: enable ctrl+p

**Comment by tmfrnz** [comment]
![image](https://github.com/dumparkltd/advocacy-tracker-client/assets/5811956/0095112a-228e-4b34-a4cf-577a721515a3)

- [ ] print header title should break/wrap like regular version

![image](https://github.com/dumparkltd/advocacy-tracker-client/assets/5811956/3491c8d9-5bb6-429b-9c75-c561bdbff6d7)

- [ ] "Configure list pages" option not working when items query arg not set

**Comment by tmfrnz** [comment]
- [ ] fix style of current list filters and add "x" icon in regular view @vbojilova 

E.g., in print-preview looks like:
![image](https://github.com/dumparkltd/advocacy-tracker-client/assets/5811956/13479268-153f-4050-8f64-119b96858065)
 
... while it should look like:
![image](https://github.com/dumparkltd/advocacy-tracker-client/assets/5811956/998662b4-818b-4a7e-893e-8f4732a054d1)

**Comment by tmfrnz** [comment]
- [ ] make sure maps do not break across pages
