### ISSUE TITLE
additional user role required "coordinator"

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/advocacy-tracker-client#151]
- can do everything that team members can do
- see confidential content [server]
- do not see archived content [server]
- can delete single items [server]
- cannot delete multiple at once [client]

also 
- allow team members to delete items they created

**Comment by tmfrnz** [comment]
@hohuuhuy can you confirm that 

- coordinators should be able to see ALL confidential content? (whereas team members can only see confidential content they created)

which would be the only difference to team members as team members also

- can not see archived content

THANKS

**Comment by tmfrnz** [comment]
see https://github.com/dumparkltd/advocacy-tracker-server/issues/67

**Comment by hohuuhuy** [comment]
> @hohuuhuy can you confirm that
> 
> * coordinators should be able to see ALL confidential content? (whereas team members can only see confidential content they created)
> 
> which would be the only difference to team members as team members also
> 
> * can not see archived content
> 
> THANKS

I confirm this is correct, thanks!

**Comment by tmfrnz** [comment]
see #157 for deleting "own" content
