### ISSUE TITLE
allow deleting own content for team members and coordinators

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/advocacy-tracker-client#157]

**Comment by tmfrnz** [comment]
- [x] ActionEdit
- [ ] ActorEdit
- [ ] CategoryEdit
- [ ] IndicatorEdit
- [ ] ResourceEdit

**Comment by vbojilova** [comment]
Role: Coordinators/ Team Member (can delete own, can't delete others)
- [ ]  ActionEdit 
- [ ]  ActorEdit
- [ ]  CategoryEdit
- [ ]  IndicatorEdit
- [ ]  ResourceEdit
Role: Admin (can delete own, can delete others)
- [ ]  ActionEdit 
- [ ]  ActorEdit
- [ ]  CategoryEdit
- [ ]  IndicatorEdit
- [ ]  ResourceEdit
Role: Analyst/Visitor (can't delete)
- [ ]  ActionEdit 
- [ ]  ActorEdit
- [ ]  CategoryEdit
- [ ]  IndicatorEdit
- [ ]  ResourceEdit
