### ISSUE TITLE
List filters: options from different option groups should be combined exclusively 

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/advocacy-tracker-client#213]
results fulfill all conditions

**Comment by JensHenningBreivik** [comment]
A new requirement/desired functionality has come up regarding this: the ability to filter for specific countries only, e.g. you want to compare the positions of 3 countries specifically. Can one accommodate for this quite easily?

**Comment by tmfrnz** [comment]
> A new requirement/desired functionality has come up regarding this: the ability to filter for specific countries only, e.g. you want to compare the positions of 3 countries specifically. Can one accommodate for this quite easily?

thanks @JensHenningBreivik, please see https://github.com/dumparkltd/advocacy-tracker-client/issues/190#issuecomment-2451584447
