### ISSUE TITLE
Various tasks INC5

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/advocacy-tracker-client#229]
### Style general

- [x] TBD: make checkboxes consistent @tmfrnz

### Primary Navigation

- [x] add hover state for "user" and "more" menu buttons similar to main menu items @vbojilova 
- [x] Responsive: apply latest design @tmfrnz

### Secondary Navigation

- [x] disable hover effect for active menu items, also mouse pointer should be the default cursor not the hand @vbojilova

**Comment by tmfrnz** [comment]
List info

- [ ] vertically align info icon
![image](https://github.com/user-attachments/assets/96c56036-b225-4994-bc29-5a60b3d4a80f)

**Comment by tmfrnz** [comment]
- [ ] hide header items when not logged in

**Comment by tmfrnz** [comment]
- [x] BUG: clear multiple list filters not working

**Comment by tmfrnz** [comment]
- [ ] review (and clean up print views) @vbojilova

**Comment by JensHenningBreivik** [comment]
![Image](https://github.com/user-attachments/assets/b5b732aa-d535-433c-bab3-c7a26a16e022)

Sorry if this is not the right task, but is it on purpose that the top navigation has become centered instead of left oriented?

**Comment by tmfrnz** [comment]
> Sorry if this is not the right task, but is it on purpose that the top navigation has become centered instead of left oriented?

yes, as per design
![image](https://github.com/user-attachments/assets/aadded2b-6d4c-446b-a61a-6f38ef8330e2)

**Comment by tmfrnz** [comment]
![Image](https://github.com/user-attachments/assets/a34d17b8-878e-4c34-8d1b-bfb79201771d)
- [ ]  fix button focus in menu
