### ISSUE TITLE
Update list views to show most relevant information 

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/advocacy-tracker-client#24]
e.g. latest positions

**Comment by tmfrnz** [comment]
### activities

- [ ] make sure a sensible tab is always selected

**Comment by tmfrnz** [comment]
@hohuuhuy please specify preferred order of columns

**Comment by hohuuhuy** [comment]
> @hohuuhuy please specify preferred order of columns

on statement page: Topics --> support --> authority --> actors  --> users

**Comment by tmfrnz** [comment]
actions

- [ ] add "related action" filter
