### ISSUE TITLE
Consider removing number from "level of authority" category (and use alternative sorting)

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/advocacy-tracker-client#245]

**Comment by tmfrnz** [comment]
apply to other ordered taxonomies

**Comment by JensHenningBreivik** [comment]
I would need a similar fix to the 'Topics' as we still would like to have a specific ordering for the topics, e.g. at the Positions dashboard. I'm trying to make the titles to the Topics shorter now, and more in line with the GPN. But e.g. GLOBAL RULES now fell downwards on the list (from being 1 - Global rules before, always on top). 
Similarly, an option to say it's part of our 'must-haves' would be very useful!

**Comment by JensHenningBreivik** [comment]
![Image](https://github.com/user-attachments/assets/f5e469ff-a12a-4737-be81-2a344a2ac7f7)
It doesn't look like this has been updated for 'Level of authority' yet?

**Comment by tmfrnz** [comment]
> It doesn't look like this has been updated for 'Level of authority' yet?

now it has (possible in the categories admin section)
