### ISSUE TITLE
Allow linking interactions with "expressions" 

### ISSUE THREAD

**Issue by tmfrnz** [dumparkltd/advocacy-tracker-client#32]
~~will require determining taxonomy "types of position expression" to allow also reflecting "level of authority"~~

- ~~official positions~~
- ~~inofficial positions~~
- ~~own assessments~~
- ~~hearsay positions~~

 see #34

**Comment by tmfrnz** [comment]
@hohuuhuy would you say that 

- interactions belong to expressions (expression being the parent/top action), OR
- expressions belong to interactions (interaction being the top action)?

**Comment by hohuuhuy** [comment]
I would say that it's the first one — if we're thinking of interactions as a source of information, that can be a reference point similar to those of, for example, actual statements from States during a conference, their official declaration at a forum, etc.,

Do you think that makes sense? we can discuss more in our catch-up if need to

**Comment by tmfrnz** [comment]
if the interaction is regarded as the source, then I would suggest to treat is as a top/parent activity. happy to discuss
